name: KillCount
version: 1.3
main: com.unlucky4ever.killcount.KillCount

commands:
  kc:
    description: Display your kills and deaths
  kdr:
    description: Display your kill/death ratio
  kca:
    description: Admin Commands
    
permissions:
  killcount.*:
    description: Access to all KillCount commands
    default: op
    children:
      killcount.kill: true
      killcount.death: true
      killcount.ratio: true
      killcount.ratio.others: true
      killcount.kc: true
      killcount.kc.others: true
      killcount.kc.top: true
      killcount.kc.reset: true
      killcount.admin.empty: true
      killcount.admin.reset: true
  killcount.use:
    description: Allows you to use the basics of KillCount
    default: true
    children:
      killcount.kill: true
      killcount.death: true
      killcount.ratio: true
      killcount.kc: true
      killcount.kc.top: true
      killcount.kc.reset: true
  killcount.admin:
    description: Allows access to all admin commands
    default: op
    children:
      killcount.admin.empty: true
      killcount.admin.reset: true
  killcount.kill:
    description: Allows your kills to be logged
    default: op
  killcount.death:
    description: Allows your deaths to be logged
    default: op
  killcount.ratio:
    description: Allows you to view your kill/death ratio
    default: op
  killcount.ratio.others:
    description: Allows you to view other players kill/death ratio
    default: op
  killcount.kc:
    description: Allows you to view your kill/death count
    deafult: op
  killcount.kc.others:
    description: Allows you to view other players kills/death count
    default: op
  killcount.kc.top:
    description: Allows you to view the top 5 killers
    default: op
  killcount.kc.reset:
    description: Allows you to reset your stats
    default: op
  killcount.admin.empty:
    description: Allows access to empty the database
    default: op
  killcount.admin.reset:
    description: Allows you to reset another players kill/death count to 0
    default: op